name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android

    - name: Build Android APK
      run: cordova build android --release || cordova build android

    - name: List APK folder contents
      run: ls -R platforms/android/app/build/outputs/apk/ || echo "No APK folder found"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          platforms/android/app/build/outputs/apk/release/*.apk
          platforms/android/app/build/outp
